version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    working_dir: /app
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:my-secret-pw@localhost:3306/nextjs
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    restart: always

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "5775:5775/udp"
#      - "16686:16686"
#      - "14268:14268"
#    restart: always

volumes:
  mysql-data:
  redis-data:
