version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-full-stack-nextjs-dev:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data-full-stack-nextjs-dev:/data
    restart: always

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    ports:
#      - "6831:6831/udp"
#      - "5775:5775/udp"
#      - "16686:16686"
#      - "14268:14268"
#    restart: always

volumes:
  mysql-data-full-stack-nextjs-dev:
  redis-data-full-stack-nextjs-dev: