import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/providers'
import { ReactNode } from 'react'
import { cs } from '@/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cs(inter.className, 'Oh!-body')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
