import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/app/providers'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth'
import NotLogin from '@/app/components/client/NotLogin'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{session ? children : <NotLogin />}</Providers>
      </body>
    </html>
  )
}
